<?php

namespace App\Controller\Admin;

use App\Entity\Category;
use App\Entity\Game;
use Doctrine\ORM\EntityManagerInterface;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Event\BeforeEntityPersistedEvent;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ChoiceField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateField;
use EasyCorp\Bundle\EasyAdminBundle\Field\NumberField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class GameCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Game::class;
    }


    public function configureFields(string $pageName): iterable
    {
        return [
            TextField::new('name')->setLabel("Nom"),
            TextField::new('catName')->setLabel('Catégorie')->onlyOnIndex(),
            NumberField::new('cardsNumber')->setLabel('Nombre de cartons')->onlyOnIndex(),
            AssociationField::new("category")->setRequired(True)->onlyOnForms(),
            NumberField::new('redCards')->setLabel('Rouge')->onlyOnIndex(),
            NumberField::new('yellowCards')->setLabel('Jaune')->onlyOnIndex(),
            DateField::new("gameDate")->setLabel("Date")->setFormat('dd/MM/Y'),
        ];
    }

    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->setDefaultSort(["category"=>'ASC','gameDate' => "DESC"]);
    }
    public function persistEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {
        if(is_null($entityInstance->getCategory())){
            $cat = $this->getDoctrine()->getRepository(Category::class)->findOneBy([]);
            $entityInstance->setCategory($cat);
        }
        parent::persistEntity($entityManager, $entityInstance); // TODO: Change the autogenerated stub
    }
    public function updateEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {
        if(is_null($entityInstance->getCategory())){
            $cat = $this->getDoctrine()->getRepository(Category::class)->findOneBy([]);
            $entityInstance->setCategory($cat);
        }
        parent::persistEntity($entityManager, $entityInstance); // TODO: Change the autogenerated stub
    }

}
